name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permitir execução do Maven Wrapper
        run: chmod +x mvnw || true

      - name: Build do projeto
        run: ./mvnw clean install

      - name: Executar testes
        run: ./mvnw test